### ISSUE TITLE
Add plot theme

### ISSUE THREAD

**Issue by davidsantiagoquevedo** [epiverse-trace/vaccineff#32]
Add consistent plot theme to vaccineff, to avoid multiple definitions of sizes, colors, etc, inside the plot functions.

**Comment by Bisaloo** [comment]
This is also a need that has been expressed by others in the project. Is there opportunity to have a global theme or do you envision this to be quite specific to vaccineff?

**Comment by davidsantiagoquevedo** [comment]
@Bisaloo The needs for vaccineff at this point are quite basic, and I was thinking of making it to respond to them. However, I would be open to using a global theme and contribute to it.

**Comment by chartgerink** [comment]
@davidsantiagoquevedo can we consider this issue still active or is it superceded by the work on [`epiversetheme`](https://github.com/epiverse-trace/epiversetheme)?

**Comment by davidsantiagoquevedo** [comment]
Yes @chartgerink. We'll add the [epiversetheme](https://github.com/epiverse-trace/epiversetheme). I'll close it.
