### ISSUE TITLE
Dynamic matching

### ISSUE THREAD

**Issue by fsabrilb** [epiverse-trace/vaccineff#37]
In order to apply the semiparametric Cox model of vaccine effectiveness, it is necessary to make a population match of the study population according to some covariates such as age and sex. For this reason, it would be useful to apply a population matching method on the cohorts that is dynamic over time in order to have scenarios that are closer to what is required for the Cox model.

**Comment by davidsantiagoquevedo** [comment]
@fsabrilb I replaced the example dataset with a new one that includes a date column for death by other causes (`death_other_causes`) to work with censoring, and an anonymous ID (`id`) to match the cases. I will have to compress this data in the future, but for now, it is enough to work on the examples for dynamic matching. Please install the package from the branch associated with this issue using: `pak::pak(epiverse-trace/vaccineff/tree/37-dynamic-matching)`

**Comment by davidsantiagoquevedo** [comment]
Solved in https://github.com/epiverse-trace/vaccineff/pull/57
