### ISSUE TITLE
vacc_date_col does not accept more than one variable

### ISSUE THREAD

**Issue by ErikaCantor** [epiverse-trace/vaccineff#48]
Please place an "x" in all the boxes that apply
---------------------------------------------

- [x ] I have the most recent version of linelist and R
- [x ] I have found a bug
- [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
- [ ] I want to request a new feature

--------

 vacc_date_col does not accept more than one variable

```r
Error in .subset2(x, i, exact = exact) : subscript out of bounds

start_cohort <- as.Date("2044-01-01")
end_cohort <- as.Date("2044-12-31")
date_interval <- c(start_cohort, end_cohort)
coh_coverage(
  data = cohortdata,
  vacc_date_col = c("vaccine_date_1","vaccine_date_2"),
  unit = "month",
  date_interval = date_interval
)
```

--------

**Comment by davidsantiagoquevedo** [comment]
This error is fixed in the new pipeline introduced to vaccineff in version v0.0.4 by removing most of the arguments and passing only the `vaccineff_data` object. See dev branch https://github.com/epiverse-trace/vaccineff/tree/make-vaccineff-data
