### ISSUE TITLE
Simplifying output cohort effectiveness

### ISSUE THREAD

**Issue by ErikaCantor** [epiverse-trace/vaccineff#49]
The output should be simplified to reduce the redundancy between VE and hazard ratio. In addition, the Schoenfeld test should be reported in a different table.  An example of the output:

| VE | lower .95 | upper .95 |
Schoenfeld test for Proportional Hazards: p-value

**Comment by davidsantiagoquevedo** [comment]
Solved in https://github.com/epiverse-trace/vaccineff/pull/57
