### ISSUE TITLE
R-CMD-check / unixOS not passing

### ISSUE THREAD

**Issue by davidsantiagoquevedo** [epiverse-trace/vaccineff#59]
Please place an "x" in all the boxes that apply
---------------------------------------------

- [x] I have the most recent version of vaccineff and R
- [x] I have found a bug
- [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
- [ ] I want to request a new feature

--------

I encountered errors with snapshots when running R-CMD checks. I set a fixed seed to avoid this issue, and the tests work on Windows but not on Ubuntu/macOS.

See: https://github.com/epiverse-trace/vaccineff/actions/runs/9528509173/job/26323163065?pr=57

**Comment by jpavlich** [comment]
Hi @davidsantiagoquevedo I talked to @GeraldineGomez  about this and I guess the best solution is to avoid using snapshots for this test. Instead, it would be better to test that the absolute difference between values is less than a threshold (e.g. 1e-2). I you agree I will implement a helper function to do this comparison.

**Comment by davidsantiagoquevedo** [comment]
Hi @jpavlich, thanks for the comment! Yeah, that sounds better. Let me know if you need any help.

**Comment by jpavlich** [comment]
@davidsantiagoquevedo  I see that you have done lots of changes to tests in the branch `refac-effectiveness-matching`. Since I need to modify those tests I will wait until you have updated `main` with those changes. Let me know when you do it

Don't worry if said test still fails, since I will fix it as soon as you update main.

**Comment by Bisaloo** [comment]
Note that [`expect_snapshot_value()`](https://testthat.r-lib.org/reference/expect_snapshot_value.html) has a `tolerance` argument. Can we use this? It would prevent having to write custom code which then needs to be maintained.

**Comment by jpavlich** [comment]
@Bisaloo good to know that. I will do the change. Thanks
