### ISSUE TITLE
rename effectiveness object as vaccineff

### ISSUE THREAD

**Issue by davidsantiagoquevedo** [epiverse-trace/vaccineff#83]
This idea was raised by @chartgerink to make it easier for users to understand the use of this object.
> Why not call this a `vaccineff` object? Effectiveness seems harder to understand if not in the direct context of the package (for example, in a pipeline). In that situation it is unclear what it relates to, potentially.
(https://github.com/epiverse-trace/vaccineff/pull/76#discussion_r1773298996)

**Comment by davidsantiagoquevedo** [comment]
Hi @chartgerink,

I’m going through this issue and would appreciate your opinion on a design decision. How good of a practice is it to name an object the same as the package? I’m currently renaming the object `effectiveness` to `vaccineff` and the function `effectiveness` to `estimate_vaccineff`, which does seem clearer.

For examples, though, should I avoid practices like `vaccineff <- estimate_vaccineff(vaccineff_data, at = 60)`? Would it be better to use something like `ve <- estimate_vaccineff(vaccineff_data, at = 60)` instead?

**Comment by chartgerink** [comment]
Hi @davidsantiagoquevedo – objects themselves is no problem as it is arbitrary. Classes named after the package is a pattern we have occur more frequently throughout Epiverse (for example, **linelist** package provides `linelist` class).

If it is only an object, and not a class name, there really is no prescription. It helps if they are self-descriptive, so it is easy to understand what is being handled. 

I do not remember my original comment exactly, but I think I meant to say the class, not the object, sorry if that caused confusion in the meantime.

**Comment by davidsantiagoquevedo** [comment]
Thanks for your clarification @chartgerink. Yes, as you probably noticed in PR #96 I renamed the class `vaccineff` and I decided to use `ve` as the default name of the objects in examples because it is more self-descriptive.
